2020-08-04 16:42:21.061 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-04 16:42:21.067 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-04 16:42:21.068 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-04 16:42:21.297 | INFO     | hagworm.extend.asyncio.net:send_request:175 - POST http://dev.jiayouxueba.cn:8080/api/member/external/teacher/signin => status:200
2020-08-04 16:42:21.301 | ERROR    | __main__:parse:66 - The unknown error of client, Exception is 'bytes' object has no attribute 'get'
2020-08-04 16:42:23.303 | INFO     | hagworm.frame.stress_tests:_func:75 - 
|  EventName  |  SuccessTotal  |  FailureTotal  |  SuccessRatio  |  SuccessAveTime  |  SuccessMinTime  |  SuccessMaxTime  |
|-------------|----------------|----------------|----------------|------------------|------------------|------------------|

2020-08-04 16:42:23.304 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
