2020-08-04 15:54:43.314 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-04 15:54:43.323 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-04 15:54:43.325 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-04 15:54:43.327 | ERROR    | hagworm.extend.base:__exit__:965 - 'Task' object has no attribute 'loop_time'
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 74, in _func
    await func(*args, **kwargs)
          │     │       └ {}
          │     └ (1, 1)
          └ <bound method Runner.run of <hagworm.frame.stress_tests.Runner object at 0x7faf7787e890>>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 185, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7faf7bea4b10>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.run() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/login.py:83> excepti...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7faf7bea4b10>
               │       └ <function gather at 0x7faf7a15e200>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/login.py", line 92, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7faf7bea4cd0>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.parse() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/login.py:44> excep...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7faf7bea4cd0>
               │       └ <function gather at 0x7faf7a15e200>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/login.py", line 46, in parse
    request_start_time = self.loop_time()
                         └ <__main__.Task object at 0x7faf7bea4b90>

AttributeError: 'Task' object has no attribute 'loop_time'
2020-08-04 15:54:43.337 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
